// angular-architects/module-federation-vanilla-shell/remotes/projects/mfe2/src/bootstrap.ts
import { createApplication } from '@angular/platform-browser';
import { createCustomElement } from '@angular/elements';
import { AppComponent } from './app/app.component';
import { provideZoneChangeDetection } from '@angular/core';
import 'zone.js';

createApplication({ providers: [provideZoneChangeDetection({ eventCoalescing: true })]})
    .then((app) => {
        const wc = createCustomElement(AppComponent, { injector: app.injector });
        customElements.define('mfe-two', wc);
    })
    .catch((err) => console.error(err));

// angular-architects/module-federation-vanilla-shell/remotes/projects/mfe1/src/bootstrap.ts
import { createApplication } from '@angular/platform-browser';
import { createCustomElement } from '@angular/elements';
import { AppComponent } from './app/app.component';

import 'zone.js';

createApplication()
    .then((app) => {
        const wc = createCustomElement(AppComponent, { injector: app.injector });
        customElements.define('mfe-one', wc);
    })
    .catch((err) => console.error(err));
